export const SITE_URL = "https://highriskintel.com";

export const SITE_NAME = "HighRiskIntel";

export const DEFAULT_OG_IMAGE = "/opengraph-image";

export const PUBLIC_ROUTES = [
  "",
  "/product",
  "/pricing",
  "/security",
  "/docs",
  "/blog",
  "/blog/what-is-chargeback-threshold",
  "/blog/how-to-prevent-mid-termination",
  "/blog/high-risk-merchant-guide",
  "/blog/chargeback-prevention-high-risk-merchants",
  "/blog/visa-vamp-2026-guide",
  "/blog/ethoca-verifi-chargeback-alerts",
  "/blog/mid-termination-warning-signs",
  "/blog/chargeback-remediation-plan",
  "/blog/rolling-reserve-explained",
  "/blog/payment-processor-hold",
  "/blog/friendly-fraud-prevention",
  "/blog/billing-descriptor-chargebacks",
  "/blog/high-risk-merchant-account-shutdown",
  "/risk-audit",
  "/high-risk",
  "/llms.txt",
  "/ai.txt",
  "/tools/chargeback-rate-calculator",
  "/industries/supplement-merchants",
  "/industries/subscription-merchants",
  "/industries/travel-merchants",
  "/industries/cbd-merchants",
  "/industries/peptide-merchants",
  "/industries/sarms-merchants",
  "/industries/kratom-merchants",
  "/industries/adult-merchants",
  "/industries/gaming-merchants",
  "/industries/forex-merchants",
  "/industries/dropshipping-merchants",
  "/industries/coaching-merchants",
  "/industries/online-course-merchants",
  "/industries/nutraceutical-merchants",
  "/industries/vape-merchants",
  "/industries/prop-trading-merchants",
  "/blog/chargeback-reason-codes-guide",
  "/blog/chargeback-representment-guide",
  "/blog/mastercard-chargeback-programs-guide",
  "/blog/high-risk-merchant-account-approval",
  "/blog/offshore-merchant-account-guide",
  "/blog/payment-processor-underwriting",
  "/blog/3d-secure-liability-shift",
  "/blog/merchant-category-codes-high-risk",
  "/blog/card-not-present-fraud-prevention",
  "/blog/chargeback-ratio-calculation",
  "/blog/high-risk-payment-gateway-guide",
  "/blog/merchant-account-reserve-types",
  "/blog/acquirer-risk-review-guide",
  "/blog/chargeback-evidence-documentation",
  "/contact",
  "/privacy",
  "/terms",
  "/about",
  "/how-it-works",
  "/case-studies",
  "/partners",
  "/processor-fund-hold",
] as const;

export const BLOG_POSTS = [
  {
    slug: "chargeback-remediation-plan",
    title: "How to Write a Chargeback Remediation Plan Your Processor Will Take Seriously",
    description:
      "A practical guide to building a chargeback remediation plan with metrics, root causes, fixes, owners, and timelines before your processor escalates.",
    datePublished: "2026-04-19",
    dateModified: "2026-04-19",
    tag: "Processor Risk",
    readTime: "9 min read",
    priority: 0.92,
  },
  {
    slug: "rolling-reserve-explained",
    title: "Rolling Reserve Explained: What High-Risk Merchants Need to Watch",
    description:
      "Learn how rolling reserves affect cash flow, why processors use them, and which warning signs merchants should monitor before reserve pressure gets worse.",
    datePublished: "2026-04-19",
    dateModified: "2026-04-19",
    tag: "Reserves",
    readTime: "8 min read",
    priority: 0.9,
  },
  {
    slug: "payment-processor-hold",
    title: "Payment Processor Holding Funds? What High-Risk Merchants Should Check First",
    description:
      "A focused checklist for merchants dealing with payout holds, reserve changes, processor questions, or sudden account review.",
    datePublished: "2026-04-19",
    dateModified: "2026-04-19",
    tag: "Processor Holds",
    readTime: "8 min read",
    priority: 0.9,
  },
  {
    slug: "friendly-fraud-prevention",
    title: "Friendly Fraud Prevention for High-Risk Merchants",
    description:
      "How to reduce friendly fraud by fixing billing descriptors, customer communication, refund timing, fulfillment proof, and subscription confusion.",
    datePublished: "2026-04-19",
    dateModified: "2026-04-19",
    tag: "Friendly Fraud",
    readTime: "8 min read",
    priority: 0.88,
  },
  {
    slug: "billing-descriptor-chargebacks",
    title: "Billing Descriptor Chargebacks: How Confusion Turns Into Disputes",
    description:
      "Learn why unclear billing descriptors create chargebacks and what merchants can do to reduce not-recognized disputes.",
    datePublished: "2026-04-19",
    dateModified: "2026-04-19",
    tag: "Descriptors",
    readTime: "7 min read",
    priority: 0.86,
  },
  {
    slug: "high-risk-merchant-account-shutdown",
    title: "What to Do If Your High-Risk Merchant Account Might Be Shut Down",
    description:
      "A practical first-response guide for merchants facing processor review, elevated chargebacks, payout holds, or possible account shutdown.",
    datePublished: "2026-04-19",
    dateModified: "2026-04-19",
    tag: "MID Protection",
    readTime: "9 min read",
    priority: 0.9,
  },
  {
    slug: "chargeback-prevention-high-risk-merchants",
    title: "Chargeback Prevention for High-Risk Merchants: The 2026 Playbook",
    description:
      "A practical 2026 playbook for high-risk merchants to reduce chargebacks, monitor Visa VAMP and Mastercard ECP exposure, use alerts, and protect their MID.",
    datePublished: "2026-04-07",
    dateModified: "2026-04-07",
    tag: "Chargeback Prevention",
    readTime: "14 min read",
    priority: 0.95,
  },
  {
    slug: "visa-vamp-2026-guide",
    title: "Visa VAMP 2026 Guide: Thresholds, Formula, and Merchant Action Plan",
    description:
      "Understand Visa's VAMP ratio, April 2026 merchant thresholds, enumeration monitoring, and the operational steps merchants should take before enforcement creates processor risk.",
    datePublished: "2026-04-07",
    dateModified: "2026-04-07",
    tag: "Visa VAMP",
    readTime: "9 min read",
    priority: 0.9,
  },
  {
    slug: "ethoca-verifi-chargeback-alerts",
    title: "Ethoca vs Verifi Alerts: How High-Risk Merchants Stop Disputes Early",
    description:
      "Learn how Ethoca Alerts, Verifi CDRN, RDR, and dispute deflection help high-risk merchants resolve disputes before they become chargebacks.",
    datePublished: "2026-04-07",
    dateModified: "2026-04-07",
    tag: "Dispute Alerts",
    readTime: "8 min read",
    priority: 0.88,
  },
  {
    slug: "mid-termination-warning-signs",
    title: "MID Termination Warning Signs: 12 Signals Your Processor Is Getting Nervous",
    description:
      "Spot the early warning signs of processor risk before a reserve hike, rolling hold, or MID termination notice catches your high-risk business off guard.",
    datePublished: "2026-04-07",
    dateModified: "2026-04-07",
    tag: "MID Protection",
    readTime: "8 min read",
    priority: 0.88,
  },
  {
    slug: "what-is-chargeback-threshold",
    title: "Visa & Mastercard Chargeback Thresholds Explained (2026)",
    description:
      "Visa's chargeback threshold is 1.8% (termination). Mastercard's is 1.0%. Learn what the thresholds are, what happens when you breach them, and how to stay safe.",
    datePublished: "2026-04-05",
    dateModified: "2026-04-05",
    tag: "Chargebacks",
    readTime: "6 min read",
    priority: 0.85,
  },
  {
    slug: "how-to-prevent-mid-termination",
    title: "How to Prevent MID Termination: 9 Steps That Actually Work",
    description:
      "MID termination is almost always preventable. Learn 9 specific actions high-risk merchants can take to protect their merchant account from processor shutdown.",
    datePublished: "2026-04-03",
    dateModified: "2026-04-03",
    tag: "MID Protection",
    readTime: "8 min read",
    priority: 0.85,
  },
  {
    slug: "high-risk-merchant-guide",
    title: "The Complete Guide to High-Risk Merchant Accounts in 2026",
    description:
      "Learn what makes a merchant account high-risk, which industries qualify, how to find a processor, what fees to expect, and how to keep your account alive.",
    datePublished: "2026-04-01",
    dateModified: "2026-04-01",
    tag: "Getting Started",
    readTime: "10 min read",
    priority: 0.85,
  },
  {
    slug: "chargeback-reason-codes-guide",
    title: "Chargeback Reason Codes Explained: Visa, Mastercard, and Amex (2026)",
    description:
      "A complete breakdown of Visa, Mastercard, and Amex chargeback reason codes — what each one means, what evidence you need, and how to reduce repeat disputes.",
    datePublished: "2026-04-20",
    dateModified: "2026-04-20",
    tag: "Chargebacks",
    readTime: "12 min read",
    priority: 0.93,
  },
  {
    slug: "chargeback-representment-guide",
    title: "Chargeback Representment Guide for High-Risk Merchants",
    description:
      "How to fight chargebacks that are worth disputing — evidence requirements by reason code, rebuttal letter structure, win-rate benchmarks, and when to refund instead.",
    datePublished: "2026-04-20",
    dateModified: "2026-04-20",
    tag: "Representment",
    readTime: "11 min read",
    priority: 0.91,
  },
  {
    slug: "mastercard-chargeback-programs-guide",
    title: "Mastercard ECP and BRAM: What High-Risk Merchants Need to Know in 2026",
    description:
      "Understand Mastercard's Excessive Chargeback Program and BRAM thresholds, what happens when you exceed them, and how to stay below limits.",
    datePublished: "2026-04-20",
    dateModified: "2026-04-20",
    tag: "Mastercard",
    readTime: "9 min read",
    priority: 0.9,
  },
  {
    slug: "high-risk-merchant-account-approval",
    title: "How to Get a High-Risk Merchant Account Approved in 2026",
    description:
      "A step-by-step guide to improving your approval odds — what processors check, how to prepare your documents, and what kills applications before they start.",
    datePublished: "2026-04-20",
    dateModified: "2026-04-20",
    tag: "Getting Started",
    readTime: "10 min read",
    priority: 0.92,
  },
  {
    slug: "offshore-merchant-account-guide",
    title: "Offshore Merchant Accounts: What They Are and When to Use One",
    description:
      "When domestic processors decline your industry, offshore merchant accounts become an option. Learn what they cost, how they work, and what risks to manage.",
    datePublished: "2026-04-20",
    dateModified: "2026-04-20",
    tag: "Payment Solutions",
    readTime: "10 min read",
    priority: 0.89,
  },
  {
    slug: "payment-processor-underwriting",
    title: "Payment Processor Underwriting: What They Review Before Approving You",
    description:
      "A look inside processor underwriting — what triggers automatic declines, what documents matter most, and how to present your business for the fastest approval.",
    datePublished: "2026-04-20",
    dateModified: "2026-04-20",
    tag: "Processor Risk",
    readTime: "9 min read",
    priority: 0.88,
  },
  {
    slug: "3d-secure-liability-shift",
    title: "3D Secure and Liability Shift Explained for High-Risk Merchants",
    description:
      "How 3DS2 moves fraud liability from merchants to card issuers, which disputes it covers, and how high-risk merchants should implement it without hurting conversion.",
    datePublished: "2026-04-20",
    dateModified: "2026-04-20",
    tag: "Fraud Prevention",
    readTime: "8 min read",
    priority: 0.87,
  },
  {
    slug: "merchant-category-codes-high-risk",
    title: "High-Risk Merchant Category Codes (MCCs): What They Mean for Your Account",
    description:
      "Some MCCs flag a business as high-risk automatically. Learn which MCCs carry extra scrutiny, how MCC assignment affects reserves and rates, and what to do about it.",
    datePublished: "2026-04-20",
    dateModified: "2026-04-20",
    tag: "Getting Started",
    readTime: "8 min read",
    priority: 0.86,
  },
  {
    slug: "card-not-present-fraud-prevention",
    title: "Card-Not-Present Fraud Prevention for High-Risk Merchants",
    description:
      "CNP fraud hits high-risk merchants hardest. Learn the signals to screen, the rules to set, and the tools that reduce fraud without blocking legitimate orders.",
    datePublished: "2026-04-20",
    dateModified: "2026-04-20",
    tag: "Fraud Prevention",
    readTime: "9 min read",
    priority: 0.87,
  },
  {
    slug: "chargeback-ratio-calculation",
    title: "How to Calculate Your Chargeback Ratio the Way Processors Do",
    description:
      "Processors use specific formulas to calculate your chargeback ratio — and they're not always what you'd expect. Learn how Visa, Mastercard, and acquirers calculate it.",
    datePublished: "2026-04-20",
    dateModified: "2026-04-20",
    tag: "Chargebacks",
    readTime: "7 min read",
    priority: 0.86,
  },
  {
    slug: "high-risk-payment-gateway-guide",
    title: "High-Risk Payment Gateways: How to Choose the Right One",
    description:
      "Not every gateway supports high-risk merchants. Learn what to look for, what red flags to avoid, and how gateway choice affects your chargeback ratio and processor relationship.",
    datePublished: "2026-04-20",
    dateModified: "2026-04-20",
    tag: "Payment Solutions",
    readTime: "9 min read",
    priority: 0.87,
  },
  {
    slug: "merchant-account-reserve-types",
    title: "Types of Merchant Account Reserves (and How to Negotiate Better Terms)",
    description:
      "Rolling reserves, capped reserves, and upfront reserves each work differently. Learn how each type is calculated, when processors apply them, and how to get reserves released.",
    datePublished: "2026-04-20",
    dateModified: "2026-04-20",
    tag: "Reserves",
    readTime: "9 min read",
    priority: 0.88,
  },
  {
    slug: "acquirer-risk-review-guide",
    title: "Acquirer Risk Reviews: What Triggers Them and How to Pass",
    description:
      "Acquirer risk reviews happen when your ratios, volume, or product category raise concerns. Learn what triggers a review, what they look for, and how to prepare.",
    datePublished: "2026-04-20",
    dateModified: "2026-04-20",
    tag: "Processor Risk",
    readTime: "9 min read",
    priority: 0.88,
  },
  {
    slug: "chargeback-evidence-documentation",
    title: "Chargeback Evidence Documentation: What Actually Wins Disputes",
    description:
      "Generic evidence loses. Learn exactly what documents win by reason code, how to structure a rebuttal packet, and what processors and banks look for when reviewing submissions.",
    datePublished: "2026-04-20",
    dateModified: "2026-04-20",
    tag: "Representment",
    readTime: "10 min read",
    priority: 0.89,
  },
] as const;

export function absoluteUrl(path = "") {
  return `${SITE_URL}${path}`;
}
